### PR TITLE
fix: IdTokenCredentials should fetch license id claim when requested

### LINKED ISSUE #1449: IdTokenCredentials fails to fetch license id claim when requested
#### Steps to reproduce

  1. Create `ComputeEngineCredentials` on a GCE VM.
  2. Derive `IdTokenCredentials` from the above with `#setOptions()` containing `IdTokenProvider.Option.LICENSES_TRUE` and optionally the implied `IdTokenProvider.Option.FORMAT_FULL`.
  3. Observe lack of license id claims in payload.

#### Code example

```java
new String(Base64.getUrlDecoder()
        .decode(IdTokenCredentials.newBuilder()
            .setIdTokenProvider(ComputeEngineCredentials.create())
            .setTargetAudience("https://foo.bar")
            .setOptions(Arrays.asList(
                IdTokenProvider.Option.FORMAT_FULL,
                IdTokenProvider.Option.LICENSES_TRUE))
            .build()
            .refreshAccessToken()
            .getTokenValue()
            .split("\\.")[1]),
    StandardCharsets.UTF_8)
```

### PR DESCRIPTION
**Pull request by sjvanrossum**
Fixes #1449 ☕️

### CODE REVIEW

File: oauth2_http/javatests/com/google/auth/oauth2/MockMetadataServerTransport.java [hunk 1]
```diff
@@ -271,14 +275,14 @@ public LowLevelHttpResponse execute() {
     if (queryPairs.containsKey("format")) {
       if (((String) queryPairs.get("format")).equals("full")) {
 
-        // return license only if format=full is set
-        if (queryPairs.containsKey("license")) {
-          if (((String) queryPairs.get("license")).equals("TRUE")) {
+        // return licenses only if format=full is set
+        if (queryPairs.containsKey("licenses")) {
+          if (BOOL_PARAMETER_VALUE.matcher((String) queryPairs.get("licenses")).matches()) {
```
Comment (lqiu96) [inline oauth2_http/javatests/com/google/auth/oauth2/MockMetadataServerTransport.java:280]: qq, why is `BOOL_PARAMETER_VALUE` Pattern needed here?

Comment (sjvanrossum) [reply oauth2_http/javatests/com/google/auth/oauth2/MockMetadataServerTransport.java:280]: @lqiu96 sorry for the wait! `BOOL_PARAMETER_VALUE` captures all values that the GCE metadata server accepts as true for a boolean query component (numeric: `1`, case sensitive: `on`, case insensitive: `y`, `yes`, `true`) or false if unmatched. I only added it to mock the behavior of the GCE metadata server accurately even though the library will only send `TRUE` in a request.

Comment (lqiu96) [reply oauth2_http/javatests/com/google/auth/oauth2/MockMetadataServerTransport.java:280]: Ah, ok. Would you be able link to any documentation on the boolean query values that MDS accepts (on,y, etc.)? If it doesn't exist, could you add a small comment to explain the above for future maintainers?

**Review by lqiu96 — APPROVED** [review]

File: oauth2_http/javatests/com/google/auth/oauth2/MockMetadataServerTransport.java (hunk 1 above)
Comment (sjvanrossum) [reply oauth2_http/javatests/com/google/auth/oauth2/MockMetadataServerTransport.java:280]: The MDS calls `::cloud_cluster::metadata_parsing_utils::GetBoolQueryComponentDefault`. I can leave a `//google3/...` reference here, but that wouldn't be helpful to external users.
My suggestion would be to reference the Abseil docs since `GetBoolQueryComponentDefault` is (currently) just `::absl::SimpleAtob` extended with matches for `on` and `off`.

```suggestion
          // The metadata server defaults to false and matches "on", "off" and ::absl::SimpleAtob.
          // See https://abseil.io/docs/cpp/guides/strings#numericConversion for more information.
          if (BOOL_PARAMETER_VALUE.matcher((String) queryPairs.get("licenses")).matches()) {
```

**Review by lqiu96 — APPROVED** [review]
