### PR TITLE
fix: Handle optional fields with null JSON value in ExternalAccountCredentials gracefully

### LINKED ISSUE #1705: ExternalAccountCredentials.fromStream() throws exception on optional fields with null value
#### Steps to reproduce

  1. Try to load the following JSON configuration using ExternalAccountCredentials.fromStream()

```json
{
  "service_account_impersonation_url": null, //optional field, would be similar with any other
  "audience": "audience",
  "subject_token_type": "subjectTokenType",
  "credential_source": {"file":"file"}
}
```

#### Code example

```java
  ExternalAccountCredentials credentials = ExternalAccountCredentials.fromStream(
          new ByteArrayInputStream(("""
                  {\
                  "service_account_impersonation_url": null,\
                  "audience": "audience",\
                  "subject_token_type": "subjectTokenType",\
                  "credential_source": {"file":"file"}\
                  }""").getBytes()));
```

#### Stack trace
```
com.google.auth.oauth2.CredentialFormatException: An invalid input stream was provided.

	at com.google.auth.oauth2.ExternalAccountCredentials.fromStream(ExternalAccountCredentials.java:398)
	at com.google.auth.oauth2.ExternalAccountCredentials.fromStream(ExternalAccountCredentials.java:366)
	at com.google.auth.oauth2.ExternalAccountCredentialsTest.fromStream_nullOptionalField(ExternalAccountCredentialsTest.java:153)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:232)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:55)
Caused by: java.lang.ClassCastException: class java.lang.Object cannot be cast to class java.lang.String (java.lang.Object and java.lang.String are in module java.base of loader 'bootstrap')
	at com.google.auth.oauth2.ExternalAccountCredentials.fromJson(ExternalAccountCredentials.java:422)
	at com.google.auth.oauth2.ExternalAccountCredentials.fromStream(ExternalAccountCredentials.java:396)
	... 28 more```

#### Any additional information below

This is caused by com.google.api.client.json.JsonParser used to parse the JSON payload.
This implementation does not deserializes null JSON value to null reference in Java, instead using magic null objects from com.google.api.client.util.Data => this causes this ClassCastException when trying to deserialize, as the magic object can't be cast to the expected field type.

The current behavior does not follow the principle of least astonishment, that be that a null value for a specific optional field in JSON configuration is just considered as missing.

This issue is likely to happen for other types of JSON credential configuration that have optional values.

### PR DESCRIPTION
**Pull request by clementdenis**
This PR handles correctly JSON null values for optional fields in ExternalAccountCredentials configuration.

This is likely a partial fix, other credential classes have the same issue (just search for `(String) json.get(` in the codebase).

The approach might applied to all json fields, including required ones, to avoid ClassCastException and have better errors.

Fixes #1705 ☕️

### CODE REVIEW

File: oauth2_http/java/com/google/auth/oauth2/ExternalAccountCredentials.java [hunk 1]
```diff
@@ -481,6 +482,14 @@ static ExternalAccountCredentials fromJson(
         .build();
   }
 
+  private static <T> T getOptional(Map<String, Object> json, String fieldName, Class<T> clazz) {
+    Object value = json.get(fieldName);
+    if (value == null || Data.isNull(value)) {
+      return null;
+    }
```
Comment (lqiu96) [inline oauth2_http/java/com/google/auth/oauth2/ExternalAccountCredentials.java:489]: qq, why the need for an additional `Data.isNull(value)` check?

File: oauth2_http/java/com/google/auth/oauth2/ExternalAccountCredentials.java [hunk 2]
```diff
@@ -481,6 +482,14 @@ static ExternalAccountCredentials fromJson(
...
+    return clazz.cast(value);
```
Comment (lqiu96) [inline oauth2_http/java/com/google/auth/oauth2/ExternalAccountCredentials.java:490]: Can we just cast this as a `(String)` when we return? Or is there a specific reason to use `Class.cast()`?

**Comment by lqiu96** [comment]
For the PR, can you update title to use [convention commits](https://www.conventionalcommits.org/en/v1.0.0/)? I think can just add a `fix: ...` prefix to the title.

Also, I think the linter CI is failing. Can you run `mvn fmt:format` on this change?

File: oauth2_http/java/com/google/auth/oauth2/ExternalAccountCredentials.java (hunk 1 above)
Comment (lqiu96) [reply oauth2_http/java/com/google/auth/oauth2/ExternalAccountCredentials.java:489]: Oh nvm. I see after pulling this down locally.

Comment (lqiu96) [reply oauth2_http/java/com/google/auth/oauth2/ExternalAccountCredentials.java:489]: Not entirely sure why the value comes back as an `Object` instead of null and I'm not too familiar with the parser inside the http-client. I don't think this check adds any harm since null values from the file wouldn't have worked and this allows the client to gracefully continue for optional fields.

**Comment by lqiu96** [comment]
Adding @aeitzman for review on 3pi code.

File: oauth2_http/java/com/google/auth/oauth2/ExternalAccountCredentials.java (hunk 2 above)
Comment (clementdenis) [reply oauth2_http/java/com/google/auth/oauth2/ExternalAccountCredentials.java:490]: It's also handling impersonationOptionsMap, which is a Map, not a String.

**Review by lqiu96 — APPROVED** [review]
LGTM. @aeitzman to review as a 3PI reviewer in case I'm missing any context about ExternalAccountCredentials and null values.

**Comment by lqiu96** [comment]
Adding a different reviewer as there have been some changes.
