### PR TITLE
fix: expiration time of the ImpersonatedCredentials token depending on the current host's timezone

### LINKED ISSUE #931: OAuth2: Expiration time of the ImpersonatedCredentials token depends on the current host's timezone
#### Environment details

1. OS type and version: All
2. Java version: 1.8
3.  version(s): 1.7.0 and before

#### Steps to reproduce

  1. Set the `TZ` environment variable to `America/Los_Angeles` (or any other timezone that is not GMT)
  2. Retrieve an access token with the AWS workload identity federation credentials
  3. Expiration time of the OAuth2 token will be incorrectly saved as 8 hours (or other value depending on the timezone set previously) from the moment it was requested instead of 1 hour, which is the actual requested lifetime.

#### Code example
There's an integration test for AWS workload identity federation [here](https://github.com/googleapis/google-auth-library-java/blob/c8c3073790ca2f660eabd2c410b0e295f693040b/oauth2_http/javatests/com/google/auth/oauth2/ITWorkloadIdentityFederationTest.java#L111)

#### External references such as API reference guides

- The [generateAccessToken API documentation](https://cloud.google.com/iam/docs/reference/credentials/rest/v1/projects.serviceAccounts/generateAccessToken) where the default maximum 1 hour lifetime is specified as well as:
- The [line of code](https://github.com/googleapis/google-auth-library-java/blob/c8c3073790ca2f660eabd2c410b0e295f693040b/oauth2_http/java/com/google/auth/oauth2/ExternalAccountCredentials.java#L218) where the lifetime of the token is set to 3600 seconds

#### Additional information
The cause of the issue was traced to the following [constant](https://github.com/googleapis/google-auth-library-java/blob/main/oauth2_http/java/com/google/auth/oauth2/ImpersonatedCredentials.java#L94)

`private static final String RFC3339 = "yyyy-MM-dd'T'HH:mm:ss'Z'";`

Since the constant defines the format to expect a literal 'Z' in the text string, it is ignoring whatever timezone definition is present in the input string returned from the STS response.

According to the javadoc for SimpleDateFormat ([see](https://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html#iso8601timezone)), the correct value for this constant should be `"yyyy-MM-dd'T'HH:mm:ssX"`, as shown in this `jshell` session (note my machine timezone is CEST):

```
jshell> var format = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss'Z'")
format ==> java.text.SimpleDateFormat@fe8ba6fa

jshell> format.parse("2022-06-22T11:14:52Z")
$3 ==> Wed Jun 22 11:14:52 CEST 2022 <-------- Zulu timezone ignored, local tz is assumed

jshell> var format = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ssX")
format ==> java.text.SimpleDateFormat@faabb35e

jshell> format.parse("2022-06-22T11:14:52Z")
$5 ==> Wed Jun 22 13:14:52 CEST 2022 <------- Zulu timezone is assumed
```
Will create a PR with the small change. Thanks!

### PR DESCRIPTION
**Pull request by ivan-f-n**
Fix bug in `ImpersonatedCredentials` class where the date received as `expirationTime` was being incorrectly parsed, assuming the date was in the host's timezone instead of reading from the date string what timezone it was.

Fixes #931 ☕️

### CODE REVIEW

**Comment by TimurSadykov** [comment]
@lsirac can't you please take a look, possibly something applicable to other languages

**Comment by lsirac** [comment]
@aeitzman

File: oauth2_http/javatests/com/google/auth/oauth2/ImpersonatedCredentialsTest.java [hunk 1]
```diff
@@ -562,6 +565,57 @@ void refreshAccessToken_delegates_success() throws IOException, IllegalStateExce
...
+
+  @Test
+  void refreshAccessToken_PDT_dateParsedCorrectly() throws IOException, IllegalStateException {
+
+    Calendar c = Calendar.getInstance();
+    c.add(Calendar.SECOND, VALID_LIFETIME);
+
+    mockTransportFactory.transport.setTargetPrincipal(IMPERSONATED_CLIENT_EMAIL);
+    mockTransportFactory.transport.setAccessToken(ACCESS_TOKEN);
+    mockTransportFactory.transport.setExpireTime(
```
Comment (aeitzman) [inline oauth2_http/javatests/com/google/auth/oauth2/ImpersonatedCredentialsTest.java:601]: Don't think this is what needs to actually be tested here. The behavior is not based off what the access token is returned with (that should always be GMT time), but what the system time zone is. Rather than returning an expiration time with a different time zone format, this test should be mocking the system time zone.

**Review by aeitzman — CHANGES_REQUESTED** [review]

File: oauth2_http/javatests/com/google/auth/oauth2/ImpersonatedCredentialsTest.java [hunk 2]
```diff
@@ -562,6 +565,57 @@ void refreshAccessToken_delegates_success() throws IOException, IllegalStateExce
...
+        getFormattedTime(c.getTime(), TimeZone.getTimeZone("PDT")));
```
[the remark this answers is not in the document]
Comment (ivan-f-n) [reply oauth2_http/javatests/com/google/auth/oauth2/ImpersonatedCredentialsTest.java]: You are right, changed, thanks!

File: oauth2_http/javatests/com/google/auth/oauth2/ImpersonatedCredentialsTest.java [hunk 3]
```diff
@@ -562,6 +565,54 @@ void refreshAccessToken_delegates_success() throws IOException, IllegalStateExce
...
+        ImpersonatedCredentials.create(
+            sourceCredentials,
+            IMPERSONATED_CLIENT_EMAIL,
+            null,
+            IMMUTABLE_SCOPES_LIST,
+            VALID_LIFETIME,
+            mockTransportFactory);
+    // Set system timezone to GMT
+    targetCredentials.calendar = Calendar.getInstance(TimeZone.getTimeZone("GMT"));
+    assertEquals(
```
Comment (aeitzman) [inline oauth2_http/javatests/com/google/auth/oauth2/ImpersonatedCredentialsTest.java:587]: nit - add new line between the end of setup and the assert

File: oauth2_http/javatests/com/google/auth/oauth2/ImpersonatedCredentialsTest.java [hunk 4]
```diff
@@ -562,6 +565,54 @@ void refreshAccessToken_delegates_success() throws IOException, IllegalStateExce
...
+
+  @Test
+  void refreshAccessToken_nonGMT_dateParsedCorrectly() throws IOException, IllegalStateException {
+
+    Calendar c = Calendar.getInstance();
+    c.add(Calendar.SECOND, VALID_LIFETIME);
+
+    mockTransportFactory.transport.setTargetPrincipal(IMPERSONATED_CLIENT_EMAIL);
+    mockTransportFactory.transport.setAccessToken(ACCESS_TOKEN);
+    mockTransportFactory.transport.setExpireTime(getFormattedTime(c.getTime()));
```
Comment (aeitzman) [inline oauth2_http/javatests/com/google/auth/oauth2/ImpersonatedCredentialsTest.java:600]: can this just be getDefaultExpireTime() now since the time zone isn't get set differently?

File: oauth2_http/javatests/com/google/auth/oauth2/ImpersonatedCredentialsTest.java (hunk 3 above)
Comment (ivan-f-n) [reply oauth2_http/javatests/com/google/auth/oauth2/ImpersonatedCredentialsTest.java:588]: Done

File: oauth2_http/javatests/com/google/auth/oauth2/ImpersonatedCredentialsTest.java (hunk 4 above)
Comment (ivan-f-n) [reply oauth2_http/javatests/com/google/auth/oauth2/ImpersonatedCredentialsTest.java:601]: It can't because we need the exact `Date` instance used to generate the date string to later assert it was parsed correctly

File: oauth2_http/javatests/com/google/auth/oauth2/ImpersonatedCredentialsTest.java [hunk 5]
```diff
@@ -926,7 +977,28 @@ void serialize() throws IOException, ClassNotFoundException {
...
+    // token exchange
+    return getFormattedTime(date, TimeZone.getTimeZone("GMT"));
+  }
+
+  /**
+   * Given a {@link Date} and a desired {@link TimeZone}, it will return a string of the date
+   * formatted like <b>yyyy-MM-dd'T'HH:mm:ssX'</b> where X represents a timezone code following
+   * RFC3339 standard
+   */
+  private static String getFormattedTime(final Date date, final TimeZone timeZone) {
```
[the remark this answers is not in the document]
Comment (ivan-f-n) [reply oauth2_http/javatests/com/google/auth/oauth2/ImpersonatedCredentialsTest.java]: Removed 👍

**Review by aeitzman — APPROVED** [review]
LGTM

File: oauth2_http/java/com/google/auth/oauth2/ImpersonatedCredentials.java [hunk 6]
```diff
@@ -110,6 +111,8 @@ public class ImpersonatedCredentials extends GoogleCredentials
 
   private transient HttpTransportFactory transportFactory;
 
+  @VisibleForTesting transient Calendar calendar = Calendar.getInstance();
```
Comment (TimurSadykov) [inline oauth2_http/java/com/google/auth/oauth2/ImpersonatedCredentials.java:114]: This should be private and implemented via builder. 

Maybe you can use the same approach as custom lifetime in ServiceAccountCredentials: https://github.com/googleapis/google-auth-library-java/blob/c21ec6c952b8bb8fb8bc2e2f1b260beb330a3cd2/oauth2_http/java/com/google/auth/oauth2/ServiceAccountCredentials.java#L666

**Review by TimurSadykov — CHANGES_REQUESTED** [review]
credential should stay immutable

File: oauth2_http/java/com/google/auth/oauth2/ImpersonatedCredentials.java (hunk 6 above)
Comment (ivan-f-n) [reply oauth2_http/java/com/google/auth/oauth2/ImpersonatedCredentials.java]: Updated

**Review by TimurSadykov — APPROVED** [review]
LGTM, thanks!

**Comment by TimurSadykov** [comment]
@ivan-f-n thanks for your contribution, please also sign Google cla, it is a quick process: https://cla.developers.google.com/

**Comment by ivan-f-n** [comment]
> @ivan-f-n thanks for your contribution, please also sign Google cla, it is a quick process: https://cla.developers.google.com/

Hi @TimurSadykov, the CLA is currently being sorted out by my company, should have an update later this week. Thanks for the patience! 🙏

**Comment by ivan-f-n** [comment]
Hello @lsirac, @TimurSadykov 
The CLA has finally been sorted out, sorry for the delay, could we move forward with this PR?

**Review by TimurSadykov — APPROVED** [review]
LGTM
